spring.application.name=climalert

# Weather API
weather.api.key=${WEATHER_API_KEY}
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.location=Buenos Aires

# Mail - Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAILTRAP_USER}
spring.mail.password=${MAILTRAP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true